// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Netrom_Eco_Meal.Database;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Netrom_Eco_Meal.Migrations
{
    [DbContext(typeof(EcoMealDbContext))]
    [Migration("20260710091916_MoreSeedData")]
    partial class MoreSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Netrom_Eco_Meal.Entities.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Netrom_Eco_Meal.Entities.Business", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("BusinessTypeId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BusinessTypeId");

                    b.ToTable("Businesses");

                    b.HasData(
                        new
                        {
                            Id = new Guid("44444444-0000-0000-0000-000000000001"),
                            Address = "12 Oak Street, Cluj-Napoca",
                            BusinessTypeId = new Guid("11111111-0000-0000-0000-000000000001"),
                            Description = "Farm-to-table restaurant with daily surplus meals.",
                            Name = "Green Fork"
                        },
                        new
                        {
                            Id = new Guid("44444444-0000-0000-0000-000000000002"),
                            Address = "5 Bread Lane, Cluj-Napoca",
                            BusinessTypeId = new Guid("11111111-0000-0000-0000-000000000002"),
                            Description = "Artisan bakery with fresh bread and pastries every morning.",
                            Name = "Sunrise Bakery"
                        },
                        new
                        {
                            Id = new Guid("44444444-0000-0000-0000-000000000003"),
                            Address = "88 Central Boulevard, Cluj-Napoca",
                            BusinessTypeId = new Guid("11111111-0000-0000-0000-000000000003"),
                            Description = "Specialty coffee shop with homemade snacks.",
                            Name = "The Daily Grind"
                        },
                        new
                        {
                            Id = new Guid("44444444-0000-0000-0000-000000000004"),
                            Address = "3 Unirii Square, Cluj-Napoca",
                            BusinessTypeId = new Guid("11111111-0000-0000-0000-000000000001"),
                            Description = "Traditional Romanian home-cooking with generous portions.",
                            Name = "La Mama"
                        },
                        new
                        {
                            Id = new Guid("44444444-0000-0000-0000-000000000005"),
                            Address = "21 Flour Street, Cluj-Napoca",
                            BusinessTypeId = new Guid("11111111-0000-0000-0000-000000000002"),
                            Description = "Family-run bakery specialising in sourdough and sweet rolls.",
                            Name = "Wheat & Wonder"
                        },
                        new
                        {
                            Id = new Guid("44444444-0000-0000-0000-000000000006"),
                            Address = "7 Garden Alley, Cluj-Napoca",
                            BusinessTypeId = new Guid("11111111-0000-0000-0000-000000000003"),
                            Description = "Cosy cafe with seasonal drinks and homemade cakes.",
                            Name = "Bloom & Brew"
                        },
                        new
                        {
                            Id = new Guid("44444444-0000-0000-0000-000000000007"),
                            Address = "55 Market Road, Cluj-Napoca",
                            BusinessTypeId = new Guid("11111111-0000-0000-0000-000000000004"),
                            Description = "Local grocery store with fresh produce and ready-made meals.",
                            Name = "FreshMart"
                        },
                        new
                        {
                            Id = new Guid("44444444-0000-0000-0000-000000000008"),
                            Address = "Central Park, Cluj-Napoca",
                            BusinessTypeId = new Guid("11111111-0000-0000-0000-000000000005"),
                            Description = "Food truck serving global street-food with a local twist.",
                            Name = "Street Spoon"
                        });
                });

            modelBuilder.Entity("Netrom_Eco_Meal.Entities.BusinessType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("BusinessTypes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000001"),
                            Name = "Restaurant"
                        },
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000002"),
                            Name = "Bakery"
                        },
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000003"),
                            Name = "Cafe"
                        },
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000004"),
                            Name = "Grocery Store"
                        },
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000005"),
                            Name = "Food Truck"
                        });
                });

            modelBuilder.Entity("Netrom_Eco_Meal.Entities.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BusinessId")
                        .HasColumnType("uuid");

                    b.Property<int>("OrderNumber")
                        .HasColumnType("integer");

                    b.Property<Guid>("StatusId")
                        .HasColumnType("uuid");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BusinessId");

                    b.HasIndex("StatusId");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Netrom_Eco_Meal.Entities.OrderPackage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PackageId")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("PackageId");

                    b.ToTable("OrderPackages");
                });

            modelBuilder.Entity("Netrom_Eco_Meal.Entities.Package", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BusinessId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("PackageTypeId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("PickupEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("PickupStart")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BusinessId");

                    b.HasIndex("PackageTypeId");

                    b.ToTable("Packages");

                    b.HasData(
                        new
                        {
                            Id = new Guid("55555555-0000-0000-0000-000000000001"),
                            BusinessId = new Guid("44444444-0000-0000-0000-000000000001"),
                            Description = "A surprise selection of today's leftover dishes — always delicious.",
                            Name = "Green Fork Surprise Bag",
                            PackageTypeId = new Guid("22222222-0000-0000-0000-000000000001"),
                            PickupEnd = new DateTime(2026, 7, 4, 20, 0, 0, 0, DateTimeKind.Utc),
                            PickupStart = new DateTime(2026, 7, 4, 17, 0, 0, 0, DateTimeKind.Utc),
                            Price = 12.99m,
                            Quantity = 5
                        },
                        new
                        {
                            Id = new Guid("55555555-0000-0000-0000-000000000002"),
                            BusinessId = new Guid("44444444-0000-0000-0000-000000000001"),
                            Description = "A full meal box with a main course and side dish.",
                            Name = "Green Fork Meal Box",
                            PackageTypeId = new Guid("22222222-0000-0000-0000-000000000002"),
                            PickupEnd = new DateTime(2026, 7, 4, 20, 0, 0, 0, DateTimeKind.Utc),
                            PickupStart = new DateTime(2026, 7, 4, 17, 0, 0, 0, DateTimeKind.Utc),
                            Price = 9.99m,
                            Quantity = 3
                        },
                        new
                        {
                            Id = new Guid("55555555-0000-0000-0000-000000000003"),
                            BusinessId = new Guid("44444444-0000-0000-0000-000000000002"),
                            Description = "Assorted fresh breads and pastries from the day.",
                            Name = "Sunrise Bread Bag",
                            PackageTypeId = new Guid("22222222-0000-0000-0000-000000000003"),
                            PickupEnd = new DateTime(2026, 7, 4, 19, 0, 0, 0, DateTimeKind.Utc),
                            PickupStart = new DateTime(2026, 7, 4, 16, 0, 0, 0, DateTimeKind.Utc),
                            Price = 6.50m,
                            Quantity = 10
                        },
                        new
                        {
                            Id = new Guid("55555555-0000-0000-0000-000000000004"),
                            BusinessId = new Guid("44444444-0000-0000-0000-000000000003"),
                            Description = "Leftover sandwiches, muffins, and snacks from the cafe.",
                            Name = "Daily Grind Surprise Bag",
                            PackageTypeId = new Guid("22222222-0000-0000-0000-000000000001"),
                            PickupEnd = new DateTime(2026, 7, 4, 21, 0, 0, 0, DateTimeKind.Utc),
                            PickupStart = new DateTime(2026, 7, 4, 18, 0, 0, 0, DateTimeKind.Utc),
                            Price = 7.99m,
                            Quantity = 4
                        },
                        new
                        {
                            Id = new Guid("55555555-0000-0000-0000-000000000005"),
                            BusinessId = new Guid("44444444-0000-0000-0000-000000000004"),
                            Description = "A hearty Romanian meal with soup, main, and dessert.",
                            Name = "La Mama Meal Box",
                            PackageTypeId = new Guid("22222222-0000-0000-0000-000000000002"),
                            PickupEnd = new DateTime(2026, 7, 4, 20, 30, 0, 0, DateTimeKind.Utc),
                            PickupStart = new DateTime(2026, 7, 4, 17, 30, 0, 0, DateTimeKind.Utc),
                            Price = 11.50m,
                            Quantity = 6
                        },
                        new
                        {
                            Id = new Guid("55555555-0000-0000-0000-000000000006"),
                            BusinessId = new Guid("44444444-0000-0000-0000-000000000004"),
                            Description = "Mystery mix of leftover homemade Romanian dishes.",
                            Name = "La Mama Surprise Bag",
                            PackageTypeId = new Guid("22222222-0000-0000-0000-000000000001"),
                            PickupEnd = new DateTime(2026, 7, 4, 21, 30, 0, 0, DateTimeKind.Utc),
                            PickupStart = new DateTime(2026, 7, 4, 19, 0, 0, 0, DateTimeKind.Utc),
                            Price = 8.50m,
                            Quantity = 4
                        },
                        new
                        {
                            Id = new Guid("55555555-0000-0000-0000-000000000007"),
                            BusinessId = new Guid("44444444-0000-0000-0000-000000000005"),
                            Description = "Six assorted pastries: croissants, cinnamon rolls, and more.",
                            Name = "Wheat & Wonder Pastry Box",
                            PackageTypeId = new Guid("22222222-0000-0000-0000-000000000005"),
                            PickupEnd = new DateTime(2026, 7, 4, 18, 0, 0, 0, DateTimeKind.Utc),
                            PickupStart = new DateTime(2026, 7, 4, 15, 0, 0, 0, DateTimeKind.Utc),
                            Price = 8.00m,
                            Quantity = 8
                        },
                        new
                        {
                            Id = new Guid("55555555-0000-0000-0000-000000000008"),
                            BusinessId = new Guid("44444444-0000-0000-0000-000000000005"),
                            Description = "End-of-day selection of sourdough, rye, and whole wheat loaves.",
                            Name = "Wheat & Wonder Bread Bag",
                            PackageTypeId = new Guid("22222222-0000-0000-0000-000000000003"),
                            PickupEnd = new DateTime(2026, 7, 4, 19, 30, 0, 0, DateTimeKind.Utc),
                            PickupStart = new DateTime(2026, 7, 4, 16, 30, 0, 0, DateTimeKind.Utc),
                            Price = 5.00m,
                            Quantity = 12
                        },
                        new
                        {
                            Id = new Guid("55555555-0000-0000-0000-000000000009"),
                            BusinessId = new Guid("44444444-0000-0000-0000-000000000006"),
                            Description = "Leftover cakes, cookies, and quiches of the day.",
                            Name = "Bloom & Brew Surprise Bag",
                            PackageTypeId = new Guid("22222222-0000-0000-0000-000000000001"),
                            PickupEnd = new DateTime(2026, 7, 4, 19, 0, 0, 0, DateTimeKind.Utc),
                            PickupStart = new DateTime(2026, 7, 4, 17, 0, 0, 0, DateTimeKind.Utc),
                            Price = 6.99m,
                            Quantity = 5
                        },
                        new
                        {
                            Id = new Guid("55555555-0000-0000-0000-000000000010"),
                            BusinessId = new Guid("44444444-0000-0000-0000-000000000007"),
                            Description = "Seasonal vegetables and fruit nearing best-before — still fresh.",
                            Name = "FreshMart Veggie Box",
                            PackageTypeId = new Guid("22222222-0000-0000-0000-000000000004"),
                            PickupEnd = new DateTime(2026, 7, 4, 20, 0, 0, 0, DateTimeKind.Utc),
                            PickupStart = new DateTime(2026, 7, 4, 16, 0, 0, 0, DateTimeKind.Utc),
                            Price = 5.50m,
                            Quantity = 15
                        },
                        new
                        {
                            Id = new Guid("55555555-0000-0000-0000-000000000011"),
                            BusinessId = new Guid("44444444-0000-0000-0000-000000000008"),
                            Description = "A full street-food meal — tacos, gyros, or noodles (surprise pick).",
                            Name = "Street Spoon Meal Box",
                            PackageTypeId = new Guid("22222222-0000-0000-0000-000000000002"),
                            PickupEnd = new DateTime(2026, 7, 4, 21, 0, 0, 0, DateTimeKind.Utc),
                            PickupStart = new DateTime(2026, 7, 4, 18, 30, 0, 0, DateTimeKind.Utc),
                            Price = 10.00m,
                            Quantity = 7
                        },
                        new
                        {
                            Id = new Guid("55555555-0000-0000-0000-000000000012"),
                            BusinessId = new Guid("44444444-0000-0000-0000-000000000008"),
                            Description = "Mixed snacks, sides, and small bites leftover from the day.",
                            Name = "Street Spoon Surprise Bag",
                            PackageTypeId = new Guid("22222222-0000-0000-0000-000000000001"),
                            PickupEnd = new DateTime(2026, 7, 4, 22, 0, 0, 0, DateTimeKind.Utc),
                            PickupStart = new DateTime(2026, 7, 4, 20, 0, 0, 0, DateTimeKind.Utc),
                            Price = 5.99m,
                            Quantity = 6
                        });
                });

            modelBuilder.Entity("Netrom_Eco_Meal.Entities.PackageType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("PackageTypes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("22222222-0000-0000-0000-000000000001"),
                            Name = "Surprise Bag"
                        },
                        new
                        {
                            Id = new Guid("22222222-0000-0000-0000-000000000002"),
                            Name = "Meal Box"
                        },
                        new
                        {
                            Id = new Guid("22222222-0000-0000-0000-000000000003"),
                            Name = "Bread Bag"
                        },
                        new
                        {
                            Id = new Guid("22222222-0000-0000-0000-000000000004"),
                            Name = "Veggie Box"
                        },
                        new
                        {
                            Id = new Guid("22222222-0000-0000-0000-000000000005"),
                            Name = "Pastry Box"
                        });
                });

            modelBuilder.Entity("Netrom_Eco_Meal.Entities.Status", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Statuses");

                    b.HasData(
                        new
                        {
                            Id = new Guid("33333333-0000-0000-0000-000000000001"),
                            Name = "Pending"
                        },
                        new
                        {
                            Id = new Guid("33333333-0000-0000-0000-000000000002"),
                            Name = "Confirmed"
                        },
                        new
                        {
                            Id = new Guid("33333333-0000-0000-0000-000000000003"),
                            Name = "Completed"
                        },
                        new
                        {
                            Id = new Guid("33333333-0000-0000-0000-000000000004"),
                            Name = "Cancelled"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Netrom_Eco_Meal.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Netrom_Eco_Meal.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Netrom_Eco_Meal.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Netrom_Eco_Meal.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Netrom_Eco_Meal.Entities.Business", b =>
                {
                    b.HasOne("Netrom_Eco_Meal.Entities.BusinessType", "BusinessType")
                        .WithMany()
                        .HasForeignKey("BusinessTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BusinessType");
                });

            modelBuilder.Entity("Netrom_Eco_Meal.Entities.Order", b =>
                {
                    b.HasOne("Netrom_Eco_Meal.Entities.Business", "Business")
                        .WithMany("Orders")
                        .HasForeignKey("BusinessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Netrom_Eco_Meal.Entities.Status", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Netrom_Eco_Meal.Entities.ApplicationUser", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Business");

                    b.Navigation("Status");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Netrom_Eco_Meal.Entities.OrderPackage", b =>
                {
                    b.HasOne("Netrom_Eco_Meal.Entities.Order", "Order")
                        .WithMany("OrderPackages")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Netrom_Eco_Meal.Entities.Package", "Package")
                        .WithMany("OrderPackages")
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Package");
                });

            modelBuilder.Entity("Netrom_Eco_Meal.Entities.Package", b =>
                {
                    b.HasOne("Netrom_Eco_Meal.Entities.Business", "Business")
                        .WithMany("Packages")
                        .HasForeignKey("BusinessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Netrom_Eco_Meal.Entities.PackageType", "PackageType")
                        .WithMany()
                        .HasForeignKey("PackageTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Business");

                    b.Navigation("PackageType");
                });

            modelBuilder.Entity("Netrom_Eco_Meal.Entities.ApplicationUser", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("Netrom_Eco_Meal.Entities.Business", b =>
                {
                    b.Navigation("Orders");

                    b.Navigation("Packages");
                });

            modelBuilder.Entity("Netrom_Eco_Meal.Entities.Order", b =>
                {
                    b.Navigation("OrderPackages");
                });

            modelBuilder.Entity("Netrom_Eco_Meal.Entities.Package", b =>
                {
                    b.Navigation("OrderPackages");
                });
#pragma warning restore 612, 618
        }
    }
}
