using System.ComponentModel.DataAnnotations.Schema;

namespace Netrom_Eco_Meal.Entities;

public class Package
{
    public Guid Id { get; set; }
    public required Guid BusinessId { get; set; }
    public required Guid PackageTypeId { get; set; }
    public required string Name { get; set; }
    public required string Description { get; set; }
    public required decimal Price { get; set; }
    // Live stock: decremented when an order is confirmed, restored if it's then cancelled.
    public required int Quantity { get; set; }
    // Used to compute the "food saved" impact stats — set by the manager per package.
    public required decimal WeightKg { get; set; }
    // Vegetarian/vegan/allergen labels — free-form from Constants.DietaryTags.All, manager-set.
    public List<string> DietaryTags { get; set; } = [];
    public required DateTime PickupStart { get; set; }
    public required DateTime PickupEnd { get; set; }
    public string? ImageUrl { get; set; }
    // Set when this instance was auto-generated by a recurring template — see PackageTemplate.
    public Guid? TemplateId { get; set; }
    // Admin/manager moderation flag — hides the package from the storefront without deleting it.
    public bool IsHidden { get; set; }
    public string? HiddenReason { get; set; }
    // Set once NearExpiryNudgeService has notified interested customers — keeps the sweep from re-notifying every tick.
    public DateTime? NearExpiryNudgeSentAt { get; set; }
    // Set when a manager dismisses the markdown-pricing suggestion for this package — keeps it from reappearing on /packages.
    public DateTime? MarkdownDismissedAt { get; set; }
    [ForeignKey(nameof(BusinessId))]
    public Business Business { get; set; } = null!;
    [ForeignKey(nameof(PackageTypeId))]
    public PackageType PackageType { get; set; } = null!;
    [ForeignKey(nameof(TemplateId))]
    public PackageTemplate? Template { get; set; }
    public ICollection<OrderPackage> OrderPackages { get; set; } = [];
}